# ===============================
# SERVER
# ===============================
server.address=0.0.0.0
server.port=8080

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/campuslk?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Vishnu

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIG
# ===============================
app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_64_CHARS_MIN
app.jwt.expirationMinutes=10080
spring.jpa.open-in-view=false


